name: flutter_native_splash
description: Generates native code to customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
version: 1.1.8+3
homepage: https://github.com/jonbhanson/flutter_native_splash

flutter:
  plugin:
    platforms:
      android:
        package: net.jonhanson.flutter_native_splash
        pluginClass: FlutterNativeSplash
      ios:
        pluginClass: FlutterNativeSplash
      web:
        pluginClass: FlutterNativeSplash
        fileName: web.dart

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  image: ^3.0.2
  meta: ^1.3.0
  path: ^1.8.0
  xml: ^5.1.0
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  test: any
