name: flutter_native_splash
description: Generates native code to customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
version: 1.0.1+1
homepage: https://github.com/jonbhanson/flutter_native_splash

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  image: ^3.0.1
  xml: ^5.0.2

dev_dependencies:
  pedantic: ^1.11.0
